/* Generated by Snowball 2.2.0 - https://snowballstem.org/ */

extern struct SN_env * nepali_UTF_8_create_env(void);
extern void nepali_UTF_8_close_env(struct SN_env * z);

extern int nepali_UTF_8_stem(struct SN_env * z);
